# Generated by Django 5.2.14 on 2026-05-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=50, unique=True)),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('partial_valid_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academic_year',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.faculty')),
            ],
            options={
                'db_table': 'department',
                'unique_together': {('code', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.department')),
            ],
            options={
                'db_table': 'promotion',
                'unique_together': {('year', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('passport_photo_path', models.CharField(blank=True, max_length=512)),
                ('passport_photo_blob', models.BinaryField(blank=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('face_encoding', models.BinaryField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicyear')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.promotion')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('threshold_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('access_code_issued_at', models.DateTimeField(blank=True, null=True)),
                ('access_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_code_type', models.CharField(blank=True, choices=[('full', 'Full'), ('partial', 'Partial')], max_length=10, null=True)),
                ('final_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.academicyear')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
            options={
                'db_table': 'finance_profile',
            },
        ),
        migrations.CreateModel(
            name='FaceTrainingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(blank=True, max_length=512)),
                ('photo_blob', models.BinaryField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
            options={
                'db_table': 'face_training_photos',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_point', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('DENIED_PASSWORD', 'Denied - Password'), ('DENIED_FACE', 'Denied - Face'), ('DENIED_FINANCE', 'Denied - Finance'), ('DENIED_MULTIPLE', 'Denied - Multiple')], max_length=20)),
                ('password_validated', models.BooleanField(default=False)),
                ('face_validated', models.BooleanField(default=False)),
                ('finance_validated', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.student')),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
    ]
